### ISSUE TITLE
Heya, just a tip

### ISSUE THREAD

**Issue by hegde-atri** [alcestide/Dotfiles#1]
I saw you leave a codeium and was just browsing your dots, a lil piece of advice - you should avoid sharing your `~/.config/doom/custom.el` file as it is supposed to be generated by DoomEmacs and can sometimes contain sensitive data. So add it to your .gitignore or something.
Hope you're having a good day :)

Kind Regards,
Atri Hegde

**Comment by alcestide** [comment]
Oh thank you, I'm new to this, I'll keep that in mind! Have a good day!
